### ISSUE TITLE
What causes gpu memory increase compred to dense mode？Is this normal？

### ISSUE THREAD

**Issue by chenrui17** [IST-DASLab/sparsegpt#1]
Great job ! 
and I recurrence your code ,but i  noticed an increase in gpu memory, and i don't understand why , because According to the paper description, the model parameters have been reduced by 50%.

**Comment by Godofnothing** [comment]
@chenrui17 parameters were set to zero, but in fact the tensors occupy the same memory, since weights are stored as dense tensors

**Comment by henrywoo** [comment]
I found the model is running even slower. Is that expected? If size doesn't change and speed is slower, what is the pruning for? Did I miss anything? cc @Godofnothing

**Comment by efrantar** [comment]
As of right now, this is a research-focused repository with the goal of accurately sparsifying GPT-style models. As @Godofnothing is saying, sparse models are currently stored as dense tensors with many weights that are exactly zero. This simulates a sparse model and is standard in sparsity research. There are various other projects focused on actual size reduction and speedups for existing sparse models, e.g. [DeepSparse](https://github.com/neuralmagic/deepsparse), [XNNPACK](https://github.com/google/XNNPACK) or [CUTLASS](https://github.com/NVIDIA/cutlass) (for 2:4 sparsity).

The memory consumption and runtime of the final model should be exactly the same, perhaps some of the memory increases and slowdowns are during the sparsification process itself and/or our layer-by-layer evaluation procedure designed to evaluate large models on a single GPU?

**Comment by slush0** [comment]
Is there any howto for reduce size of the sparsed model? I tried with DeepSparse, but failed miserably. It seems there's no way how to convert back the DeepSparse-compiled model back to huggingface format.

**Comment by Alignment-Lab-AI** [comment]
> As of right now, this is a research-focused repository with the goal of accurately sparsifying GPT-style models. As @Godofnothing is saying, sparse models are currently stored as dense tensors with many weights that are exactly zero. This simulates a sparse model and is standard in sparsity research. There are various other projects focused on actual size reduction and speedups for existing sparse models, e.g. [DeepSparse](https://github.com/neuralmagic/deepsparse), [XNNPACK](https://github.com/google/XNNPACK) or [CUTLASS](https://github.com/NVIDIA/cutlass) (for 2:4 sparsity).
> 
> The memory consumption and runtime of the final model should be exactly the same, perhaps some of the memory increases and slowdowns are during the sparsification process itself and/or our layer-by-layer evaluation procedure designed to evaluate large models on a single GPU?

i know this is research focused and perhaps slightly out of scope, but if the simulation is successful, if pruning the models gives a functional implementation, it would likely generate a lot of attention/funding even if it was suboptimal
