### ISSUE TITLE
Different error between OBS and SparseGPT

### ISSUE THREAD

**Issue by sbwww** [IST-DASLab/sparsegpt#12]
Following OBS, we want to remove the weights with minimum error $w_m^2/H_{mm}^{-1}$ . But, in the SparseGPT algorithm, we use $w_m^2/{H^{-1}}_{mm}^2$ instead.

I'm not sure if it is equivalent between using $H_{mm}^{-1}$ and ${H_{mm}^{-1}}^2$ and I don't see any $w_m^2/{H_{mm}^{-1}}^2$ elsewhere in the paper. Am I missing some points about such a difference?

Below are the occurrences of this issue in the paper and code.

|OBS|SparseGPT|
|-|-|
|![image](https://github.com/IST-DASLab/sparsegpt/assets/45259695/d4d44717-9e0a-470f-bc9e-f6e8b618ac48)|![image](https://github.com/IST-DASLab/sparsegpt/assets/45259695/5ada7cec-bef6-48c2-8a7f-b6c809d72326)|

https://github.com/IST-DASLab/sparsegpt/blob/f5c25005a61f96a0933ca2f95705a963585aafaa/sparsegpt.py#L96

**Comment by sbwww** [comment]
In the v1 version of arxiv paper, it was $w_m^2/H_{mm}^{-1}$

![image](https://github.com/IST-DASLab/sparsegpt/assets/45259695/95f4099f-717b-4804-8064-63801c392d4e)

**Comment by efrantar** [comment]
Hi, the reason we take the square in the SparseGPT algorithm is that we are working with the Cholesky decomposition of the Hessian inverse, which contains the square roots of the diagonal elements  (see our [GPTQ paper](https://arxiv.org/abs/2210.17323) for more details on this trick). Hence, we square them to reconstruct the actual OBS formula. The initial arxiv version contained some typos in the pseudocode, please use the most recent version and our code for reference.

**Comment by sbwww** [comment]
OK I see.
But what about the other lines? Like, in the "// pruning error" line, should it be $W_{:,j}^2/{H_{jj}^{-1}}^2$

**Comment by efrantar** [comment]
Here we don't square because the corresponding entries in $H^{-1}$ are already divided by the sqrt of the original diagonal due to the executed Cholesky decomposition, hence defining the error in the way we do ultimately reconstructs the OBS formula also in those lines.

**Comment by sbwww** [comment]
Oh, $W_{:,j}^2/H_{jj}^{-1} \cdot H_{j,j:(i+B)}^{-1}$ eliminates the square root division.
It is very sound mathematics. Thank you very much!
