### ISSUE TITLE
Saving the pruned checkpoint?

### ISSUE THREAD

**Issue by AlpinDale** [IST-DASLab/sparsegpt#2]
Does the Bloom implementation save the pruned weights?

**Comment by Godofnothing** [comment]
@AlpinDale , no it does not

**Comment by slush0** [comment]
The last commit introduces `--save` parameter so it is possible now.

**Comment by AlpinDale** [comment]
> The last commit introduces `--save` parameter so it is possible now.

Thanks. I did manage to implement a save function in my fork, but the zeroed weights were kept so the pruned model wasn't cut in half (in terme of disk space). Does this new save function handle that?
