### ISSUE TITLE
Adaptation for Pruning Conv2d or Conv3d Layers?

### ISSUE THREAD

**Issue by satabios** [IST-DASLab/sparsegpt#22]
How would I proceed to adapt the "add_batch" function to make the pruning possible on a Conv layer? Am I missing something here.

Any suggestions are greatly appreciated. Thanks in advance.

**Comment by efrantar** [comment]
Hi, basically you have to [unfold](https://pytorch.org/docs/stable/generated/torch.nn.Unfold.html) the convolution into an equivalent linear layer, you can take a look at the implementation of our previous work OBC [here](https://github.com/IST-DASLab/OBC/blob/main/trueobs.py), which does that. I think a very similar approach should work for integrating convolutions into SparseGPT.
