### ISSUE TITLE
Why Hessian can get by activation ($H = XX^T$) ？

### ISSUE THREAD

**Issue by Beatlesso** [IST-DASLab/sparsegpt#31]
I don't really understand, isn't the Hessian matrix a second-order derivative matrix, so how can it be obtained by multiplying the activation value matrix by its transpose ($H = XX^T$) ?
Can you give me some more detailed instructions?

**Comment by efrantar** [comment]
SparseGPT operates in a layer-wise manner, solving the corresponding *layer-wise* pruning problem, given by Equation (1) in the paper. This is essentially a masked linear squared error problem of which the Hessian is indeed $XX^T$; you are right that the *whole network's* Hessian includes second-order derivatives, but the SparseGPT algorithm does not require this Hessian.

**Comment by Beatlesso** [comment]
> SparseGPT operates in a layer-wise manner, solving the corresponding _layer-wise_ pruning problem, given by Equation (1) in the paper. This is essentially a masked linear squared error problem of which the Hessian is indeed XXT; you are right that the _whole network's_ Hessian includes second-order derivatives, but the SparseGPT algorithm does not require this Hessian.



> SparseGPT operates in a layer-wise manner, solving the corresponding _layer-wise_ pruning problem, given by Equation (1) in the paper. This is essentially a masked linear squared error problem of which the Hessian is indeed XXT; you are right that the _whole network's_ Hessian includes second-order derivatives, but the SparseGPT algorithm does not require this Hessian.

Thanks for the answer, but why the Hessian for the masked linear squared error problem is $XX^T$ and how was this result derived?

**Comment by Donyme** [comment]
@Beatlesso , check the least squares estimator here: https://global.oup.com/booksites/content/0199268010/samplesec3

<img width="657" alt="Screenshot 2024-04-02 at 11 24 13 AM" src="https://github.com/IST-DASLab/sparsegpt/assets/26718351/ffb96455-e2ce-43bb-a1da-76973749f3fb">

The first order derivative of the squared loss function is as shown in equation 3.7, the second order derivative is as shown in equation 3.10 (which is essentially the same as XX<sup>T</sup> if you interchange the row and column dimension).

**Comment by Beatlesso** [comment]
> @Beatlesso , check the least squares estimator here: https://global.oup.com/booksites/content/0199268010/samplesec3
> 
> <img alt="Screenshot 2024-04-02 at 11 24 13 AM" width="657" src="https://private-user-images.githubusercontent.com/26718351/318873033-ffb96455-e2ce-43bb-a1da-76973749f3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMTA2MDAsIm5iZiI6MTcxMjExMDMwMCwicGF0aCI6Ii8yNjcxODM1MS8zMTg4NzMwMzMtZmZiOTY0NTUtZTJjZS00M2JiLWExZGEtNzY5NzM3NDlmM2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDAyMTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNjQxNTY2MDRhYjE2Yzc5OGMwNWM3Mzg4MGQ4MWQ1YjBmY2I4OGRhZTMzNWYxYjI2NTg1MWIxMWU1NDRjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WI47dku2FTeoioxFLTp23KnsHM9jQ_UCaycv6ryZHS4">
> The first order derivative of the squared loss function is as shown in equation 3.7, the second order derivative is as shown in equation 3.10 (which is essentially the same as XXT if you interchange the row and column dimension).

This is very useful, thanks!
