### ISSUE TITLE
why i can't reproduce the result of paper?

### ISSUE THREAD

**Issue by SHUSHENGQIGUI** [IST-DASLab/sparsegpt#37]
hi, i am very confused,   I am reproducing opt-1.3b sparsity. the fact is that i can get the same dense model  preplexity  at 14.62 of wikitext2, but the preplexity after sparsing 50% is 26.71, which is higher than 17.46 in paper.  And I didn't modify any code in this repo. I wonder if the hyperparams in paper's experiments are different? 
look forward to your reply.

![image](https://github.com/IST-DASLab/sparsegpt/assets/28890775/2236d348-b83b-414a-a340-2832b36b8907)

**Comment by SHUSHENGQIGUI** [comment]
> hi, i am very confused, I am reproducing opt-1.3b sparsity. the fact is that i can get the same dense model preplexity at 14.62 of wikitext2, but the preplexity after sparsing 50% is 26.71, which is higher than 17.46 in paper. And I didn't modify any code in this repo. I wonder if the hyperparams in paper's experiments are different? look forward to your reply.
> 
> ![image](https://private-user-images.githubusercontent.com/28890775/332680575-2236d348-b83b-414a-a340-2832b36b8907.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTIxNzAsIm5iZiI6MTcxNjcxMTg3MCwicGF0aCI6Ii8yODg5MDc3NS8zMzI2ODA1NzUtMjIzNmQzNDgtYjgzYi00MTRhLWEzNDAtMjgzMmIzNmI4OTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDA4MjQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZjM4ZDU3NWMxZTU4MTg4YWU4NjMyMWNiNTI3NDFmNzA2OGVmNmNiMjA3OGRkMjU3MmFlNmU1ZWY4ZmJlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgWEN_0nP4kR5AP5g7e1ydxZvBwKIrsNA5LSlGWHr4g)

@ilmarkov  hi, could you reply to me in your spare time ? i am stuck in this problem. I don't know how i reproduce the result as showed in paper. please

**Comment by efrantar** [comment]
Hi, what command are you running? Generally, the code has been running fine for many people; however, it is possible that some recent HuggingFace update broke things.

**Comment by SHUSHENGQIGUI** [comment]
> Hi, what command are you running? Generally, the code has been running fine for many people; however, it is possible that some recent HuggingFace update broke things.

Thank you for your reply. The command I run is the one in the readme. as follows:
`python opt.py facebook/opt-1.3b  wikitext2 --sparsity .5 --save ./out/opt-1.3b/sparse0.5/`

and huggingface version  i am using is  0.23.0
I can run your code succuessfully, but the results are slightly different from the results in  paper:
![image](https://github.com/IST-DASLab/sparsegpt/assets/28890775/8c5256b4-1d9f-4cc3-b5de-caee618257da)

look forward to your reply, Thanks

**Comment by efrantar** [comment]
Hi, in the paper we run with calibration data from `c4` and not `wikitext2`; the former is not only more general but I think the latter can even sometimes lead to overfitting and correspondingly bad results (possibly this is what you are seeing?).

```
python opt.py facebook/opt-1.3b c4 --sparsity .5 --save ./out/opt-1.3b/sparse0.5/
```

**Comment by SHUSHENGQIGUI** [comment]
> Hi, in the paper we run with calibration data from `c4` and not `wikitext2`; the former is not only more general but I think the latter can even sometimes lead to overfitting and correspondingly bad results (possibly this is what you are seeing?).
> 
> ```
> python opt.py facebook/opt-1.3b c4 --sparsity .5 --save ./out/opt-1.3b/sparse0.5/
> ```

Thank you. To verify if the code is wrong, I test more opt models: 
![image](https://github.com/IST-DASLab/sparsegpt/assets/28890775/a0908d12-c642-4b4b-b850-e2c7e13323b1)

as you can see, Apart from opt-1.3b, the other model results differ only slightly from the paper, So I think the code is right and most reproduced results looks normal too .
That is weird. And I can confirm there is not any modify when i test opt-1.3b. 
Besides, The table in your paper shows the result on wikitext2:
![image](https://github.com/IST-DASLab/sparsegpt/assets/28890775/c2378581-006f-4e43-9558-a7558bca1098)

**Comment by efrantar** [comment]
We evaluate on wikitext but always use c4 as calibration data (this should be noted in the paper). Yes, this is a bit weird, however there can sometimes be outlier models which do not follow the trend.

**Comment by SHUSHENGQIGUI** [comment]
> We evaluate on wikitext but always use c4 as calibration data (this should be noted in the paper). Yes, this is a bit weird, however there can sometimes be outlier models which do not follow the trend.

yes. i realize i made a mistake. i didn't use c4 as calibration data. Now I solve the problem, Thank you!!!!
