### ISSUE TITLE
Hessian Inverse

### ISSUE THREAD

**Issue by Calmepro777** [IST-DASLab/sparsegpt#6]
Hello, 

SparseGPT is really an amazing job.

I am wondering in `https://github.com/IST-DASLab/sparsegpt/blob/master/sparsegpt.py#L77`, why cholesky decomposition is performed on the inversed hessian matrix.

Thank you.

**Comment by efrantar** [comment]
Hi, the Cholesky decomposition is an efficient way to get all the information we need from the inverse Hessian sequence. Basically, it allows us to efficiently precompute all the dark yellow squares in the inverse Hessian sequence in Figure 4 in the paper in advance using existing optimized Cholesky kernels. This also helps significantly with numerical stability. You can read more about this Cholesky trick in our related [GPTQ paper](https://arxiv.org/abs/2210.17323).

**Comment by 619135593** [comment]
In the OBS formula, the calculation is done through the columns of Hinv. Why can it also be done through the rows?
