### ISSUE TITLE
Question about multi-GPU inference

### ISSUE THREAD

**Issue by lsder** [IST-DASLab/sparsegpt#9]
sparsegpt has shown good results in the A100, but for a large number of commercial GPUs, VRAM and computation power are still a big pressure. is there a necessity and idea for multi-GPU inference?

**Comment by efrantar** [comment]
Hi, SparseGPT is only concerned with sparsifying the weights of a given model, which is independent of how it is ultimately sharded for inference; e.g. you could distribute different layers on different GPUs or even shard the same, e.g. 2:4 sparse, layer across multiple devices. Please note that the actual implementation of such multi-GPU distribution is beyond the scope of this project (which is focused on accurate sparsification).
